### ISSUE TITLE
TypeError: 'NoneType' object is not a mapping in select method of DeepClient

### ISSUE THREAD

**Issue by konard** [deep-foundation/deepclient#19]
While running unittests with the following command:
```sh
( cd python && python -m unittest discover -s tests -v )
```
I encountered an error in the test_select method of the TestDeepClient class:
```
ERROR: test_select (test_deep_client.TestDeepClient.test_select)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/deepclient/python/tests/test_deep_client.py", line 144, in test_select
    loop.run_until_complete(test_async_methods())
  File "/home/gitpod/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
  File "/workspace/deepclient/python/tests/test_deep_client.py", line 141, in test_async_methods
    await self.client.select(1)
  File "/workspace/deepclient/python/deepclient/deep_client.py", line 424, in select
    "variables": {
TypeError: 'NoneType' object is not a mapping
```

This error seems to be related to the select method in the deep_client.py file, specifically at line 424. It appears that there is an issue with a NoneType object being used as a mapping.

To resolve this issue, please investigate why the mapping is of type NoneType and ensure that a valid mapping is being used. Additionally, consider adding more informative error messages or handling the case when the mapping is NoneType to prevent similar issues in the future.

**Comment by konard** [comment]
Unable to fix it with AutoPR
