### ISSUE TITLE
Error in test_select

### ISSUE THREAD

**Issue by konard** [deep-foundation/deepclient#21]
```
gitpod /workspace/deepclient (main) $ ( cd python && python -m unittest discover -s tests -v )
test_initialization (test_deep_client.TestDeepClient.test_initialization) ... ok
test_methods_raise_not_implemented (test_deep_client.TestDeepClient.test_methods_raise_not_implemented) ... /workspace/deepclient/python/tests/test_deep_client.py:38: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
ok
test_select (test_deep_client.TestDeepClient.test_select) ... ERROR
test_serialize_where (test_deep_client.TestDeepClient.test_serialize_where) ... ok

======================================================================
ERROR: test_select (test_deep_client.TestDeepClient.test_select)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/deepclient/python/tests/test_deep_client.py", line 144, in test_select
    loop.run_until_complete(test_async_methods())
  File "/home/gitpod/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/workspace/deepclient/python/tests/test_deep_client.py", line 141, in test_async_methods
    await self.client.select(1)
  File "/workspace/deepclient/python/deepclient/deep_client.py", line 419, in select
    q = await self.client.execute(generate_query({
                                  ^^^^^^^^^^^^^^^^
  File "/workspace/deepclient/python/deepclient/query.py", line 62, in generate_query
    called_queries = [m(alias, i) if callable(m) else m for i, m in enumerate(queries)]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/deepclient/python/deepclient/query.py", line 62, in <listcomp>
    called_queries = [m(alias, i) if callable(m) else m for i, m in enumerate(queries)]
                      ^^^^^^^^^^^
  File "/workspace/deepclient/python/deepclient/query.py", line 9, in inner
    defs.append(f"${field + index}: {field_types[field]}")
                    ~~~~~~^~~~~~~
TypeError: can only concatenate str (not "int") to str

----------------------------------------------------------------------
Ran 4 tests in 0.003s

FAILED (errors=1)
```

**Comment by konard** [comment]
Unable to fix the issue using AutoPR.
